### ISSUE TITLE
May I use your blog theme?

### ISSUE THREAD

**Issue by javivelasco** [aekaplan/aekaplan.github.io#4]
Hi Adam, hope it's fine to open here an Issue to ask you. Do you mind if I use your blog design for my personal site? It looks so neat and nice!! My primary intention is to modify it but I would start from your styles. Sorry to open an issue to ask you but I was not able to find an email address.

Thanks! :)

**Comment by aekaplan** [comment]
Thanks for asking. You can use my styles :)

**Comment by javivelasco** [comment]
Thanks man! :)
